export const OPCODES = {
  ENTER_SCOPE: 1,
  LEAVE_SCOPE: 2,
  REPLACE_SCOPE: 3,
  LOAD_CONST: 4,
  MOVE: 5,
  LOAD_SLOT: 6,
  INIT_SLOT: 7,
  STORE_SLOT: 8,
  LOAD_GLOBAL: 9,
  STORE_GLOBAL: 10,
  GET_PROP: 11,
  SET_PROP: 12,
  BINARY: 13,
  UNARY: 14,
  JUMP: 15,
  JUMP_IF_FALSE: 16,
  CALL: 17,
  MAKE_FUNCTION: 18,
  RETURN: 19,
  LOAD_THIS: 20,
  LOAD_ARGUMENTS: 21,
  ARRAY_NEW: 22,
  OBJECT_NEW: 23,
  ARRAY_PUSH: 24,
  OBJECT_SET: 25,
  LOAD_UNDEFINED: 26,
  NEW: 27,
  THROW: 28,
  TRY: 29,
  AWAIT: 30,
  YIELD: 31,
  JUMP_IF_NOT_NULLISH: 32,
  DELETE_PROP: 33,
  LOAD_NEW_TARGET: 34,
  TYPEOF_GLOBAL: 35,
  ABRUPT_JUMP: 36,
  NOP: 37,
} as const

export type OpcodeName = keyof typeof OPCODES

export const BINARY_OPS = {
  '+': 1,
  '-': 2,
  '*': 3,
  '/': 4,
  '%': 5,
  '==': 6,
  '===': 7,
  '!=': 8,
  '!==': 9,
  '>': 10,
  '>=': 11,
  '<': 12,
  '<=': 13,
  '&&': 14,
  '||': 15,
  '**': 16,
  '<<': 17,
  '>>': 18,
  '>>>': 19,
  '&': 20,
  '|': 21,
  '^': 22,
  'instanceof': 23,
  'in': 24,
  '??': 25,
} as const

export const UNARY_OPS = {
  '!': 1,
  '-': 2,
  '+': 3,
  typeof: 4,
  void: 5,
  // Internal operations used to preserve ToNumeric and BigInt update semantics.
  to_numeric: 6,
  '++': 7,
  '--': 8,
} as const

export type BinaryOperatorCode = (typeof BINARY_OPS)[keyof typeof BINARY_OPS]
export type UnaryOperatorCode = (typeof UNARY_OPS)[keyof typeof UNARY_OPS]
